version: '3'
services:
  web:
    build: .
    command: gunicorn adorBotProject.wsgi:application --bind 0.0.0.0:8001 --timeout 500 --workers 3
    ports:
      - "8001:8001"
    networks:
      - shared_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8000:8000"
    depends_on:
      - web
    networks:
      - shared_network

networks:
  shared_network:
    external: true
